# Generated by Django 5.0.4 on 2024-05-06 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venderapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
